package hu.csaba.numbersheet2.pdf.layout;

import hu.csaba.numbersheet2.config.AppConfig;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.IOException;
import java.time.LocalDate;

public class HeaderFooterRenderer {

    private static final PDType1Font FONT =
            new PDType1Font(Standard14Fonts.FontName.HELVETICA);

    private final AppConfig config;

    // (maradhat fixen egyelőre, később könnyen configossá tesszük)
    private final float topMargin = 40;
    private final float bottomMargin = 40;
    private final float headerHeight = 30;
    private final float footerHeight = 30;

    public HeaderFooterRenderer(AppConfig config) {
        this.config = config;
    }

    public float getTopMargin() { return topMargin; }
    public float getBottomMargin() { return bottomMargin; }
    public float getHeaderHeight() { return headerHeight; }
    public float getFooterHeight() { return footerHeight; }

    public void drawHeader(PDPageContentStream content, PDPage page) throws IOException {
        float pageWidth = page.getMediaBox().getWidth();
        float y = page.getMediaBox().getHeight() - topMargin;

        // Bal oldal: cím
        content.beginText();
        content.setFont(FONT, 12);
        content.newLineAtOffset(50, y);
        content.showText("Numbersheet Report");
        content.endText();

        // Bal oldal 2. sor: generátor infó (count + range)
        String genInfo = String.format("Count: %d | Range: %d–%d",
                config.getGeneratorCount(),
                config.getGeneratorMin(),
                config.getGeneratorMax());

        content.beginText();
        content.setFont(FONT, 10);
        content.newLineAtOffset(50, y - 12); // kicsit lejjebb
        content.showText(genInfo);
        content.endText();

        // Jobb oldal: dátum
        String date = LocalDate.now().toString();
        float fontSize = 10;

        // szöveg szélességének kiszámítása
        float textWidth = FONT.getStringWidth(date) / 1000f * fontSize;

        // jobb margóhoz igazítás
        float rightMargin = 50;
        float dateX = pageWidth - rightMargin - textWidth;
        content.beginText();
        content.setFont(FONT, 10);
        content.newLineAtOffset(dateX, y);
        content.showText(date);
        content.endText();
    }

    public void drawFooter(PDPageContentStream content, PDPage page, int pageNumber) throws IOException {
        float y = bottomMargin;

        String footer = "Page " + pageNumber + " | Generated by Numbersheet2";
        float fontSize = 10;

        float textWidth = FONT.getStringWidth(footer) / 1000f * fontSize;
        float rightMargin = 50;
        float footerX = page.getMediaBox().getWidth() - rightMargin - textWidth;

        content.beginText();
        content.setFont(FONT, fontSize);
        content.newLineAtOffset(footerX, y);
        content.showText(footer);
        content.endText();
    }
}
